### ISSUE TITLE
xl2tpd file descriptors issue

### ISSUE THREAD

**Issue by 0Roizinho** [xelerance/xl2tpd#140]
Hello,

I'm experiencing some problems due to file descriptor issues in xl2tpd service. At first time, I started to read syslog messages like 'GetPtyMaster_ptmx: unable to open /dev/ptmx', so I verify there was a fd limitation for this process in the OS, 1024 specifically. So, when it reaches near 1024 it starts to reject connections. After I setup new higher fd values for that service, it crashed without any message. 

Then, I wonder if there is any fd limitation at this point or some other detail that I overlooked since I didn't realize of any issue checking the code.
Version of xl2tpd is 1.3.6
Thanks in advance

**Comment by shussain** [comment]
@0Roizinho Does thsi issue still occur? 

If it is, can you please test 1.3.12

**Comment by jasonchang1218** [comment]
@0Roizinho 
Is this issue still occur in newer version?

**Comment by jasonchang1218** [comment]
Is this issue still occur in newer version after modifying fd?

**Comment by jasonchang1218** [comment]
Does this issue still occur in newer version after modifying fd?

**Comment by jasonchang1218** [comment]
@0Roizinho Does this issue still occur in newer version after modifying fd?
@shussain  Is there any modification against this issue in 1.3.12?

**Comment by shussain** [comment]
Hi @jasonchang1218. If I am to understand things properly, you have a similar problem to 
@0Roizinho  where you are getting "GetPtyMaster_ptmx"

If that is the case, I would suggest looking at branch libevent (which is based off xl2tpd version 1.3.10.1). It contains code that has been modified to work with more connections. The code has been tested locally but it still needed to be tested more thoroughly under real world load/use and for the code to be updated to have all the commits since 1.3.10.1 release

**Comment by 0Roizinho** [comment]
Hi @jasonchang1218 and @shussain. We could test 1.3.12 around a year ago but no succeed since it was unstable with many connections.
However, we could manage over 1024 stable conns with libevent branch, but watching over xl2tpd daemon due to some unindentified crashes.

**Comment by shussain** [comment]
Closing ticket.

@0Roizinho or @jasonchang1218 if you find any issues or crashes, you can get some more information with the --debug-signals and --debug-libevent option
